### ISSUE TITLE
Error with new ASK-SDK-Core

### ISSUE THREAD

**Issue by SSmale** [itachiRedhair/alexa-skill-local#2]
when trying to use the new sdk 2.0 i get the following error, that appears to be coming from the lambda function

```
(node:4602) UnhandledPromiseRejectionWarning: TypeError: callback is not a function
    at /Users/SSmale/Documents/GitRepos/TeaMaid/node_modules/ask-sdk-core/dist/skill/factory/BaseSkillFactory.js:176:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4602) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function withouta catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4602) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Session ended with reason: ERROR
(node:4602) UnhandledPromiseRejectionWarning: TypeError: callback is not a function
    at /Users/SSmale/Documents/GitRepos/TeaMaid/node_modules/ask-sdk-core/dist/skill/factory/BaseSkillFactory.js:176:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4602) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function withouta catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

any insight on how to fix this would be amazing

**Comment by itachiRedhair** [comment]
It looks like the new way to build skill lambda function might not work with the current package. I'll check again and come with the work around.

**Comment by itachiRedhair** [comment]
Hey @SSmale I have updated the package. You can get it from npm. Tell me if it has fixed your issue. Operation would be same as before.

**Comment by SSmale** [comment]
Wow that was insanely fast, thank you. 

I will check tonight and report back

**Comment by SSmale** [comment]
Works perfectly! thank you again.

Now to get my function to work on AWS :(

**Comment by itachiRedhair** [comment]
About this AWS issue, I'd be happy to help you by email.
